### ISSUE TITLE
SegFault after setting pretrigger=256; record length=2048

### ISSUE THREAD

**Issue by pnvn** [sevenreek/qtadqscope#11] opened 2021-10-08 10:22 UTC

**Comment by pnvn** [comment] 2021-10-08 13:09
Problem occurs even with pretrigger set to 64.

**Comment by sevenreek** [comment] 2021-10-09 11:37
Potentially fixed by #14. Likely caused by insufficient header buffer malloc.

**Closed as completed** 2021-10-09 11:41 UTC
Labels: bug, urgent
